apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: atenadb
  name: atenadb
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
      image: ghcr.io/mchl-coder/atena/atena:latest
      name: atenadb
      ports:
        - containerPort: 5001
        - containerPort: 5000
      resources: {}
      volumeMounts:
        - mountPath: /data/atena
          name: data
  restartPolicy: OnFailure
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data
status: {}
